### ISSUE TITLE
TypeScript d.ts generations fails when two or more namespaces has the same top level name

### ISSUE THREAD

**Issue by daon** [jaystack/jaydata-dynamic-metadata#5]
Let say I have a schema with the following namespaces:
- `JayData.Test.CommonItems.Entities`
- `JayData.Test.SpecialItems.Entities`

then the following will be generated in the d.ts file:

``` typescript
declare module JayData.Test.CommonItems.Entities {
}
export {JayData as JayData}

declare module JayData.Test.SpecialItems.Entities {
}
export {JayData as JayData}
```

The two lines `export {JayData as JayData}` generates the following error message: `Duplicate identifier 'JayData'`

**Comment by lazarv** [comment]
Thanks to @jpattersonz, this issue is now fixed.
